### ISSUE TITLE
参考下您的项目

### ISSUE THREAD

**Issue by ioiogoo** [ethan-funny/React-News-Board#2]
您好，看了您的项目，写的非常漂亮，目前正在学Vue.js，所以想将此项目用Vue重写一遍，前端内容大致跟这个相同，有一点小小改动，希望你不要介意：）

**Comment by ethan-funny** [comment]
你好，本项目采用 GPL-2.0 开源协议，这意味着对原项目的修改也需要开源代码，而不能闭源。也就是说，你可以参考我原来的代码，并做修改，但要保持开源，并且随源代码、二进制版附上 GPL 的许可证。

谢谢。
